### PR TITLE
added sparkup plugin, based on zencoding

### PR DESCRIPTION
**Pull request by davidreuss**
https://github.com/bingaman/vim-sparkup

http://www.youtube.com/watch?v=dB2Q9EN37eY

Want!

### CODE REVIEW

**Comment by kibs** [comment]
awesome!

**Comment by kibs** [comment]
can't automerge via this page, weird, will do manually instead

**Comment by kibs** [comment]
Manually merged!! nice plugin

**Comment by davidreuss** [comment]
Not that particularly weird since it caused a conflict.. i based the patch on the current master at the time, so the double pull-request for adding a submodule was expected not to apply cleanly :)

But thanks.

And yes. It is a nice plugin. For your frontend scaffolding needs ;)

**Pull request merged**
